#Goal : i have to lint, build, test the code for frontend and backend,
#then push the Images to docker HUb.

name: CI

on:
  push:
    branches: [master]

jobs:

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
      - name: Set up NodeJSgi
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          chache: npm
          chache-dependency-path: frontend/package-lock.json
      - name: Install npm packages
        run: npm install
        working-directory: frontend
      - name: Run Linter
        run: npm run lint
        working-directory: frontend
      - name: RUN Tests
        run: npm run test
        working-directory: frontend
